// One-off generator: emits db/seed.sql from the canonical TS seed data so the
// Postgres path stays in sync with the in-memory store. Run: node db/gen-seed.mjs
import { writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

// Import TS sources via tsx loader when run as `node --import tsx db/gen-seed.mjs`,
// or rely on a prior build. Here we re-declare the import paths dynamically.
const base = pathToFileURL(process.cwd() + '/apps/api/src/data/').href;
const { regions } = await import(base + 'regions.ts');
const { crops } = await import(base + 'crops.ts');
const { getSuitability } = await import(base + 'cropRegion.ts');

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const lines = [];
lines.push('-- Generated by db/gen-seed.mjs — do not edit by hand.');
lines.push('-- Seed: regions, crops, crop_region.\n');

lines.push('insert into regions (id, name_uz, name_ru, name_en) values');
lines.push(
  regions
    .map((r) => `  (${r.id}, ${q(r.name_uz)}, ${q(r.name_ru)}, ${q(r.name_en)})`)
    .join(',\n') + '\non conflict (id) do nothing;\n',
);

lines.push(
  'insert into crops (id, name_uz, name_ru, name_en, difficulty, water_need, min_water_level, harvest_days_min, harvest_days_max, investment_per_sotka_uzs, yield_kg_per_sotka, price_per_kg_uzs, good_for_consumption, good_for_profit, notes_uz, notes_ru) values',
);
lines.push(
  crops
    .map(
      (c) =>
        `  (${c.id}, ${q(c.name_uz)}, ${q(c.name_ru)}, ${q(c.name_en)}, ${q(c.difficulty)}, ${q(c.water_need)}, ${c.min_water_level}, ${c.harvest_days_min}, ${c.harvest_days_max}, ${c.investment_per_sotka_uzs}, ${c.yield_kg_per_sotka}, ${c.price_per_kg_uzs}, ${c.good_for_consumption}, ${c.good_for_profit}, ${q(c.notes_uz)}, ${q(c.notes_ru)})`,
    )
    .join(',\n') + '\non conflict (id) do nothing;\n',
);

const crRows = [];
for (const c of crops) {
  for (const r of regions) {
    crRows.push(`  (${c.id}, ${r.id}, ${q(getSuitability(c.id, r.id))})`);
  }
}
lines.push('insert into crop_region (crop_id, region_id, suitability) values');
lines.push(crRows.join(',\n') + '\non conflict (crop_id, region_id) do nothing;\n');

writeFileSync('db/seed.sql', lines.join('\n'));
console.log('Wrote db/seed.sql:', crRows.length, 'crop_region rows');
